language: java
jdk:
- oraclejdk8
services:
  - postgresql
  - mysql
  - mongodb
before_script:
- psql -c 'create database travis_ci_test;' -U postgres
- psql -c 'create schema j_some authorization postgres;' -U postgres travis_ci_test
- psql -c "CREATE ROLE javers LOGIN PASSWORD 'javers' SUPERUSER;" -U postgres
- psql -c 'SHOW server_version_num;' -U postgres
- mysql -e 'CREATE DATABASE travis_ci_test;' -u root
- mysql -e "CREATE USER 'javers'@'localhost' IDENTIFIED BY 'javers';" -u root
- mysql -e "GRANT ALL PRIVILEGES ON travis_ci_test.* TO 'javers'@'localhost' WITH GRANT OPTION;" -u root
- mongo --eval 'db.version();'
script:
- ./gradlew build
- ./gradlew integrationTest
deploy:
  skip_cleanup: true
  provider: script
  script: travis/deployToSonatype.sh
  on:
    tags: true
    all_branches: true
sudo: false

