language: java

script:
  - if [ $TRAVIS_BRANCH == "production" ]; then 
      ./gradlew bintrayUpload \
      -PbintrayApiKey=$bintrayApiKey \
      -PbintrayUsername=%bintrayUsername
      -PsonatypeUser=$sonatypeUser \
      -PsonatypePassword=$sonatypePassword \
      -PbintrayDryRun
    fi